<a href="https://colab.research.google.com/github/lohi629/computational_statistics/blob/main/matrix_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
R=int(input("enter no.of rows:"))
C=int(input("enter no.of columns:"))
m=[[int(input()) for i in range(C)]for j in range(R)]
def display(k):
  for i in range(R):
    for j in range(C):
      print(k[i][j],end=" ")
    print("")
display(m)


enter no.of rows:3
enter no.of columns:3
1
3
3
1
4
3
1
3
4
1 3 3 
1 4 3 
1 3 4 


In [ ]:
transpose=[[0 for i in range(C)]for j in range(R)]
for i in range(len(m)):
  for j in range(len(m[0])):
    transpose[i][j]=m[j][i]
for i in range(C):
  for j in range(R):
    print(transpose[i][j],end=" ")
  print()




1 1 1 
3 4 3 
3 3 4 


In [ ]:
n=[[int(input()) for i in range(C)]for j in range(R)]
display(n)

2
1
4
3
1
2
4
7
8
2 1 4 
3 1 2 
4 7 8 


In [ ]:
result=[[0 for i in range(C)]for j in range(R)]
for i in range(len(m)):
  for j in range(len(n[0])):
    for k in range(len(n)):
      result[i][j]=result[i][j]+(m[i][k]*n[k][j])
display(result)


23 25 34 
26 26 36 
27 32 42 


In [ ]:
import numpy as np
A = np.array([[int(input()) for i in range(C)]for j in range(R)])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

1
3
3
1
4
3
1
3
4
[[ 7. -3. -3.]
 [-1.  1.  0.]
 [-1.  0.  1.]]
