In [133]:
import pandas as pd
import numpy as np
df=pd.read_excel("C:\\Users\\y20cs95\\Desktop\\Book1.xlsx")
print(df)

      y  x1  x2  x3
0   100   1   9  62
1   110   1   8  58
2   105   1   7  64
3    94   1  14  60
4    95   1  12  63
5    99   1  10  57
6   104   1   7  55
7   108   1   4  56
8   105   1   6  59
9    98   1   5  61
10  105   1   7  57
11  110   1   6  60


In [135]:
x1=df['x1']
x2=df['x2']
x3=df['x3']
y=df['y']
print(x1)
print(x2)
print(x3)
print(y)

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
Name: x1, dtype: int64
0      9
1      8
2      7
3     14
4     12
5     10
6      7
7      4
8      6
9      5
10     7
11     6
Name: x2, dtype: int64
0     62
1     58
2     64
3     60
4     63
5     57
6     55
7     56
8     59
9     61
10    57
11    60
Name: x3, dtype: int64
0     100
1     110
2     105
3      94
4      95
5      99
6     104
7     108
8     105
9      98
10    105
11    110
Name: y, dtype: int64


In [136]:
arr1=x1.to_numpy()
arr2=x2.to_numpy()
arrx=x3.to_numpy()
arr3=y.to_numpy()
print(arr1,arr2,arr3,arrx)

[1 1 1 1 1 1 1 1 1 1 1 1] [ 9  8  7 14 12 10  7  4  6  5  7  6] [100 110 105  94  95  99 104 108 105  98 105 110] [62 58 64 60 63 57 55 56 59 61 57 60]


In [137]:
arr=np.array([arr1,arr2,arrx])
print(arr)
y_arr=np.array([arr3])
print(y_arr)

[[ 1  1  1  1  1  1  1  1  1  1  1  1]
 [ 9  8  7 14 12 10  7  4  6  5  7  6]
 [62 58 64 60 63 57 55 56 59 61 57 60]]
[[100 110 105  94  95  99 104 108 105  98 105 110]]


In [138]:
def transpose(m):
    res=[[0 for i in range(len(m))]for j in range(len(m[0]))]
    for i in range(len(m[0])):
        for j in range(len(m)):
            res[i][j]=m[j][i]
    return res

In [139]:
X=transpose(arr)
print(X)
Y=transpose(y_arr)
print(Y)

[[1, 9, 62], [1, 8, 58], [1, 7, 64], [1, 14, 60], [1, 12, 63], [1, 10, 57], [1, 7, 55], [1, 4, 56], [1, 6, 59], [1, 5, 61], [1, 7, 57], [1, 6, 60]]
[[100], [110], [105], [94], [95], [99], [104], [108], [105], [98], [105], [110]]


In [140]:
def display(m):
    for i in range(len(m)):
        for j in range(len(m[0])):
            print(m[i][j],end=" ")
        print()

In [141]:
def inverse(m):
    s=np.linalg.inv(m) 
    return s

In [142]:
def mul(m,n):
    c=[[0 for i in range(len(n[0]))]for j in range(len(m))]
    for i in range(len(m)):
        for j in range(len(n[0])):
            for k in range(len(n)):
                c[i][j]=c[i][j]+(m[i][k]*n[k][j])
    return c
        
     

In [143]:
Xtx=mul(arr,X)
display(Xtx)

12 95 712 
95 845 5663 
712 5663 42334 


In [144]:
q=mul(arr,Y)
display(q)

1233 
9636 
73094 


In [145]:
inv=inverse(Xtx)
display(inv)

40.89440259769005 0.1140465198471444 -0.7030438912328081 
0.11404651984714678 0.011751452364648463 -0.003490092995515962 
-0.7030438912328084 -0.003490092995515922 0.012314726867089485 


In [146]:
betacap=mul(inv,q)
display(betacap)

133.46048242804682 
-1.2485034569591562 
-0.351008371805392 


In [183]:
b=np.ravel(betacap)
print(b)

[133.46048243  -1.24850346  -0.35100837]


In [148]:
print("equation is:","y=",betacap[0][0],"+",betacap[1][0],"x1",betacap[2][0],"x2")

equation is: y= 133.46048242804682 + -1.2485034569591562 x1 -0.351008371805392 x2


In [150]:
yexp=y
ycal=betacap[0][0]+(betacap[1][0]*x2)+(betacap[2][0]*x3)
print(ycal)

0     100.461432
1     103.113969
2     102.256422
3      94.920932
4      96.364914
5     100.967971
6     105.415498
7     108.810000
8     105.259968
9     105.806454
10    104.713481
11    104.908959
dtype: float64


In [151]:
error=yexp-ycal
print(error)

0    -0.461432
1     6.886031
2     2.743578
3    -0.920932
4    -1.364914
5    -1.967971
6    -1.415498
7    -0.810000
8    -0.259968
9    -7.806454
10    0.286519
11    5.091041
dtype: float64


In [152]:
def sum(x):
    s=0
    for i in x:
        s=s+i
    return s

In [153]:
errorsq=error*error
sum_error=sum(errorsq)
print("sse:",sum_error)

sse: 151.41040622031764


In [154]:
ysum=sum(y)
ymean=ysum/len(y)
print(ymean)

102.75


In [157]:
ydiff=y-ymean
ydif=ydiff**2
sst=sum(ydif)
print("sst:",sst)

sst: 330.25


In [159]:
ssr=sst-sum_error
print("ssr:",ssr)

ssr: 178.83959377968236


In [160]:
coff_of_det=ssr/sst
print(coff_of_det)


0.5415279145486218


In [161]:
if(coff_of_det>0.90):
    print("good fit")
else:
    print("bad fit")

bad fit


# Anova


In [170]:
df_regression=len(betacap)-1
df_error=len(df)-len(betacap)
mean_ssr=ssr/df_regression
mean_sse=sum_error/df_error
Fcal=mean_ssr/mean_sse
print("Fcal:",Fcal)

Fcal: 5.315210440935849


In [172]:
import scipy.stats as s
Ftab=s.f.ppf(.95,df_regression,df_error)
print("tablevalue:",Ftab)

tablevalue: 4.25649472909375


In [173]:
if(Fcal>=Ftab):
    print("reject null hypothesis and accept model")
else:
    print("accept null and reject model")

reject null hypothesis and accept model


# test for parameters

In [197]:
c=[]
for i in range(len(inv)):
    for j in range(len(inv[0])):
        if(i==j):
            c.append(inv[i][j])
print(c)
            

[40.89440259769005, 0.011751452364648463, 0.012314726867089485]


In [198]:

se=[]
t=[]
for i in c:
    p=(mean_sse*i)**0.5
    se.append(p)
for i in range(len(se)):
    s=b[i]/se[i]
    t.append(abs(s))
print(t)
    
    
    

[5.088199707759956, 2.8079370633903307, 0.7711670682669088]


In [211]:
import scipy.stats as s
ttab=s.t.ppf(0.05/2,df_error)
t_tab=abs(ttab)
print(t_tab)

2.262157162740992


In [214]:
for i in t:
    if(i>=t_tab):
        print("reject null and variable is contributing to model")
    else:
        print("accept null and variable is not contributing to model")

reject null and variable is contributing to model
reject null and variable is contributing to model
accept null and variable is not contributing to model
